### ISSUE TITLE
Issue with add PopoutWindowModule into the imports array of your @NgModule

### ISSUE THREAD

**Issue by RogerPenningtonLMCO** [Shemesh/angular-popout-window#15]
Doing the line:
import { PopoutWindowModule } from 'angular-popout-window';

kicks an error saying popout-window.component.ts:28:18 - error Generic type 'Component Declaration' requires 7 type argument(s).

I'm following along with your usage here: https://www.npmjs.com/package/angular-popout-window?activeTab=readme
And I don't see this declaration being talked about here. Just says import and add to the to the @NgModule. Is there something that I am doing wrong here, or is there an issue with the package?

Any help would be greatly appreciated. Thanks

**Comment by Shemesh** [comment]
which Angular version? which angular-popout-window version?

**Comment by RogerPenningtonLMCO** [comment]
I am using angular-popout-window 4.0.0, and Angular version 13.3.11.

**Comment by Shemesh** [comment]
version 4 is for ng14+.
for ng13- you should use version 3.1.1

**Comment by RogerPenningtonLMCO** [comment]
Oooohhhh. *facepalm*
Thank you so much for the reply. I appreciate it.
