### ISSUE TITLE
Popout window is blank

### ISSUE THREAD

**Issue by leesan70** [Shemesh/angular-popout-window#4]
After migrating to the version 2.0.0, the popout window displays no content. 
The browsers tested are:
1) Version 87.0.4280.88 (Official Build) (x86_64) on macOS 11.0.1
2) Version 14.0.1 (16610.2.11.51.8) on macOS 11.0.1
3) Version 87.0.4280.88 (Official Build) (64 bit) on Windows 10

Version 1.3.0 was working fine with same set ups.

Not only on my app that this behavior is present, but also the online demo is showing the same behavior as well.

<img width="853" alt="Screen Shot 2020-12-16 at 3 14 30 PM" src="https://user-images.githubusercontent.com/20693595/102401540-818a0700-3fb1-11eb-9156-15d01512ef41.png">
<img width="855" alt="Screen Shot 2020-12-16 at 3 14 45 PM" src="https://user-images.githubusercontent.com/20693595/102401549-8353ca80-3fb1-11eb-9cca-6339b623e242.png">

**Comment by Shemesh** [comment]
😯 it works good on chrome, but not on firefox.
in v2 i started using some browser event to make things happen. 
will take a look.

**Comment by Shemesh** [comment]
my thought was to hook on the window load event, but it seems each browser have different behavior for when to dispatch this event. have to find some other way...

**Comment by Shemesh** [comment]
@leesan70 hi,
i have published a fix in v2.1.0 https://www.npmjs.com/package/angular-popout-window
please test it and let me know.

**Comment by leesan70** [comment]
Working fine on my set ups!
