### ISSUE TITLE
How to handle/catch close event

### ISSUE THREAD

**Issue by ertemmstein** [Shemesh/angular-popout-window#8]
Hi,
I want to catch close event when pressing X icon on pop-out window, is it possible?

**Comment by Shemesh** [comment]
you should register to the window close event

**Comment by ertemmstein** [comment]
thanks for answer, is there a sample code for that, i couldnt able to do that.
I pop out and pop-in with this way but cannot register to close event of PopoutWindowComponent:

  ```
popOut(popoutComp:PopoutWindowComponent){
    popoutComp.popOut();
    if(popoutComp.isPoppedOut){
      this.hidePopOutIcon = true;
    }
  }

  popIn(popoutComp:PopoutWindowComponent){
    //const { popOutWindow } = popoutComp;
    popoutComp.popIn();
    if(!popoutComp.isPoppedOut){
      this.hidePopOutIcon = false;
    }
  }
```

**Comment by Shemesh** [comment]
i mean something [like this](https://github.com/Shemesh/angular-popout-window/blob/fe9b97a95fb2ada7e29a78be79b09e82e554bcb7/projects/popout-window/src/lib/popout-window.component.ts#L37-L40)
